CREATE DATABASE     MUNDOVERDE;
use MUNDOVERDE;

CREATE TABLE PRODUTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIÇAO VARCHAR(60)NOT NULL,
    CATEGORIA INT NOT NULL,
    PREÇO FLOAT NOT NULL,
    QUANTIDADE INT NOT NULL,
    URL VARCHAR(255)
);

INSERT INTO PRODUTOS VALUES (1, 'GRANOLAS COM CASTANHAS 1KG', 0, 40.18, 6, 'cereais.png');
INSERT INTO PRODUTOS VALUES (2,'WHEY PROTEIN 907G',1, 379.39,10, 'suplementos.png');
INSERT INTO PRODUTOS VALUES (3, 'ALHO EM PÓ', 2,5.18,15, 'temperos.png');

select * from produtos;